name: 'star-wars-db-app'

services:
    database:
        attach: false
        restart: 'always'
        env_file:
            -   ./environments/.env
        ports:
            - 5432:5432
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./database/Dockerfile
    backend:
        attach: false
        restart: 'always'
        depends_on:
            -   database
        env_file:
            -   ./environments/.env
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - 3000:3000
    assets:
        attach: false
        restart: 'always'
        build: ./www/software/swdbapp/assets
        platform: linux/arm64
        ports:
            - 4000:80
