name: 'star-wars-db-app'

services:
    database:
        restart: 'always'
        env_file:
            - ./environments/.env.docker
        ports:
            - 5432:5432
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./apps/database/Dockerfile
    backend:
        restart: 'always'
        depends_on:
            - database
        env_file:
            - ./environments/.env.docker
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./apps/backend/Dockerfile
        ports:
            - 3000:3000
    assets:
        restart: 'always'
        build: ./www/software/swdbapp/assets
        platform: linux/arm64
        ports:
            - 4000:4000
    # web:
    #     restart: 'always'
    #     depends_on:
    #         - database
    #         - backend
    #         - assets
    #     env_file:
    #         - ./environments/.env.docker
    #     build:
    #         context: .
    #         dockerfile: ./apps/frontend/vue-js
    #     ports:
    #         - 8080:80
