name: 'star-wars-db-app'

services:
    database:
        restart: 'always'
        env_file:
            - .env/.env.docker
        ports:
            - 5432:5432
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./apps/database/Dockerfile
    backend:
        restart: 'always'
        depends_on:
            - database
        env_file:
            - .env/.env.docker
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./apps/backend/Dockerfile
        ports:
            - 3000:3000
    assets:
        restart: 'always'
        build: ./apps/assets
        platform: linux/arm64
        ports:
            - 4000:80
    web:
        restart: 'always'
        depends_on:
            - database
            - backend
            - assets
        env_file:
            - .env/.env.docker
        environment:
            VITE_ASSETS_PATH: "${VITE_ASSETS_PATH}"
            VITE_API_KEY: "${VITE_API_KEY}"
            VITE_API_HOST: "${VITE_API_HOST}"
            VITE_API_PORT: "${VITE_API_PORT}"
            VITE_API_PROTOCOL: "${VITE_API_PROTOCOL}"
        build:
            context: .
            dockerfile: ./apps/frontend/vue-js/Dockerfile
            args:
                VITE_ASSETS_PATH: "${VITE_ASSETS_PATH}"
                VITE_API_KEY: "${VITE_API_KEY}"
                VITE_API_HOST: "${VITE_API_HOST}"
                VITE_API_PORT: "${VITE_API_PORT}"
                VITE_API_PROTOCOL: "${VITE_API_PROTOCOL}"
        ports:
            - 8080:80
