name: swdbapp

services:
    swdbapp-database:
        attach: false
        restart: 'always'
        env_file:
            -   ./environments/.env.development
        ports:
            - 5432:5432
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./database/Dockerfile
    swdbapp-backend:
        attach: false
        restart: 'always'
        depends_on:
            -   swdbapp-database
        env_file:
            -   ./environments/.env.development
        platform: linux/arm64
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        ports:
            - 3000:3000
    swdbap-assets:
        attach: false
        restart: 'always'
        build: ./www/software/swdbapp/assets
        platform: linux/arm64
        ports:
            - 4000:80
