export default {
	plugins: ['@trivago/prettier-plugin-sort-imports'],
	printWidth: 120,
	tabWidth: 4,
	useTabs: true,
	semi: true,
	singleQuote: true,
	quoteProps: 'as-needed',
	jsxSingleQuote: false,
	trailingComma: 'es5',
	bracketSpacing: true,
	bracketSameLine: true,
	arrowParens: 'avoid',
	endOfLine: 'lf',
	singleAttributePerLine: false,
	htmlWhitespaceSensitivity: 'css',
    importOrder: ['^.+/(.*).(sa|sc|c)ss$', '^@?(vue|react).+', '^@swdbapp/(.*)$', '^@/(.*)', '^../(.*)', '^./'],
	importOrderSeparation: false,
	importOrderSortSpecifiers: true,
};
