/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

/**
 * The type of the title
 */
export type TitleType = 'films' | 'games-apps' | 'series';

export const TITLE_TYPE: Record<string, TitleType> = Object.freeze({
	Films: 'films' as TitleType,
	GamesApps: 'games-apps' as TitleType,
	Series: 'series' as TitleType,
});
