/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

import type { TitleItem } from './title-item.model';

export interface TitlesListResponse {
	/**
	 * Limit of items returned
	 */
	limit: number;
	/**
	 * Offset for current request
	 */
	offset: number;
	/**
	 * Total number of titles in database
	 */
	total: number;
	items: Array<TitleItem>;
}
