/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

/**
 * Short detail of a title
 */
export interface TitleItem {
	/**
	 * Unique title identifier
	 */
	id: number;
	/**
	 * Title name
	 */
	name: string;
	/**
	 * Partial URL path to title image
	 */
	logo: string;
}
