/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

/* model.mustache */

/**
 * Age rating (e.g., PG-13, R) of a title
 */
export type TitleRating = 'G' | 'PG' | 'PG-13' | 'R' | 'NC-17';

export const TITLE_RATING: Record<string, TitleRating> = Object.freeze({
	G: 'G' as TitleRating,
	Pg: 'PG' as TitleRating,
	Pg13: 'PG-13' as TitleRating,
	R: 'R' as TitleRating,
	Nc17: 'NC-17' as TitleRating,
});
