/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

import type { TitleType } from './title-type.model';
import type { TitleRating } from './title-rating.model';

export interface TitleDetailResponse {
	/**
	 * Unique title identifier
	 */
	id: number;
	/**
	 * Title name
	 */
	name: string;
	/**
	 * Partial URL path to title image
	 */
	logo: string;
	type: TitleType;
	/**
	 * Partial URL of the title poster
	 */
	poster: string;
	rating: TitleRating;
	/**
	 * Time in milliseconds that express the title duration. Only applies for \'films\' or \'series\' types.
	 */
	duration: string;
	/**
	 * Date in which title was released.
	 */
	releaseDate: string;
	/**
	 * Genres that matches with title content.
	 */
	genre: string;
	/**
	 * Sort intro to title content
	 */
	resume: string;
	/**
	 * Director of the title
	 */
	director: string;
	/**
	 * Music director of the title
	 */
	musicDirector: string;
	/**
	 * List of title\'s producers
	 */
	producers: string;
	/**
	 * List of title\'s actors
	 */
	actors: string;
	/**
	 * The whole plot of the title, in HTML syntax.
	 */
	plot: string;
	/**
	 * Title\'s opening crawl text, in HTML syntax
	 */
	openingCrawl: string;
}
