/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

import { BaseHttpClient } from '@swdbapp/types';
import { XHR_FETCH_METHODS } from '@amjs/js-utils';
import { provideAPIHeaders } from '@swdbapp/core-feature';
import type { EraDetailResponse } from '../models';
import type { ErasListResponse } from '../models';

export interface ErasEraDetailsInput {
	/** Unique era identifier */
	id: string;
}

export interface ErasErasListInput {
	/** Max. number of elements to return */
	limit?: number;
	/** Index or pointer where to start filtering */
	offset?: number;
	/** Field to order */
	orderBy?: string;
	/** Direction of the ordering. Could be:  - \&#39;asc\&#39; for ascending order - \&#39;desc\&#39; for descending order  */
	orderDir?: string;
	/** Value to use as search criteria */
	search?: string;
	/** Field from era model to use as search criteria */
	searchBy?: string;
}

export interface ErasHttpClient {
	/**
	 * Returns details of an era
	 *
	 * @param input Request parameters
	 */
	details(input: ErasEraDetailsInput): Promise<EraDetailResponse | Error>;

	/**
	 * List all available eras
	 *
	 * @param input Request parameters
	 */
	list(input?: ErasErasListInput): Promise<ErasListResponse | Error>;
}

export class DefaultErasHttpClient extends BaseHttpClient implements ErasHttpClient {
	/**
	 * @override
	 */
	protected _serialize(
		headers?: Record<string, string>,
		body?: object | number | string | boolean | null
	): Promise<void | Error> {
		return super._serialize(
			{
				...(headers || {}),
				...provideAPIHeaders(),
			},
			body
		);
	}

	async details({ id }: ErasEraDetailsInput): Promise<EraDetailResponse | Error> {
		return this.fetch<EraDetailResponse>(`/eras/${id}`, {
			method: XHR_FETCH_METHODS.GET,
		});
	}

	async list({ limit, offset, orderBy, orderDir, search, searchBy }: ErasErasListInput = {}): Promise<
		ErasListResponse | Error
	> {
		return this.fetch<ErasListResponse>(`/eras`, {
			method: XHR_FETCH_METHODS.GET,
			params: { limit, offset, orderBy, orderDir, search, searchBy },
		});
	}
}
