/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

/**
 * Short detail of an era
 */
export interface EraItem {
	/**
	 * Unique era identifier
	 */
	id: number;
	/**
	 * Era name
	 */
	name: string;
	/**
	 * URL path to era image
	 */
	image: string;
}
