/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

import type { EraTitle } from './era-title.model';

/**
 * Detailed information of an Era
 */
export interface EraDetailResponse {
	/**
	 * Unique era identifier
	 */
	id: number;
	/**
	 * Era name
	 */
	name: string;
	/**
	 * URL path to era image
	 */
	image: string;
	/**
	 * Description of the era
	 */
	description: string;
	titles: Array<EraTitle>;
}
