/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

export interface EraTitle {
	/**
	 * Order of the title within the era. Starts in zero (0).
	 */
	order: number;
	/**
	 * Title
	 */
	title: string;
	/**
	 * Partial URL of the title\'s logo asset
	 */
	logo: string;
}
