/**
 * @NOTICE: This file has been auto generated by SWDBApp OpenAPI generator.
 *
 * Do not edit the file manually!
 */

import type { EraItem } from './era-item.model';

export interface ErasListResponse {
	/**
	 * Limit of items returned
	 */
	limit: number;
	/**
	 * Offset for current request
	 */
	offset: number;
	/**
	 * Total number of eras in database
	 */
	total: number;
	items: Array<EraItem>;
}
